<?php

/**
 * @file
 * Contains console_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function console_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the console_entity module.
    case 'help.page.console_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function console_entity_theme() {
  $theme = [];
  $theme['console_entity'] = [
    'render element' => 'elements',
    'file' => 'console_entity.page.inc',
    'template' => 'console_entity',
  ];
  $theme['console_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'console_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function console_entity_theme_suggestions_console_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#console_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'console_entity__' . $sanitized_view_mode;
  $suggestions[] = 'console_entity__' . $entity->bundle();
  $suggestions[] = 'console_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'console_entity__' . $entity->id();
  $suggestions[] = 'console_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
